### ISSUE TITLE
Please add semantic version tags

### ISSUE THREAD

**Issue by arytbk** [berzniz/Sequencer#2]
Congrats for your great Sequencer class!

Could you please add a suitable version tag (such as 1.0.0) to use with cocoapods.org ?

Thanks,
Ary

**Comment by berzniz** [comment]
Thanks.

Fork it, pull request it -> I will add it :)

**Comment by arytbk** [comment]
Just did!

Once you approve it I'll add the podspec file (I already prepared) to the cocoa pods.org repo...

**Comment by berzniz** [comment]
Approved. Thanks for taking the time to contribute.

If there is also something worth adding to the README in order to explain about the pod integration, let me know.

**Comment by arytbk** [comment]
You need to add a tag with exact text "1.0.0" - apparently it was not imported with the pull request…
Then I'll upload the spec file to cocoapods and once approved, I'll send you the few lines to add to the README.

**Comment by berzniz** [comment]
I added a 1.0.0 tag

**Comment by arytbk** [comment]
Thanks! I sent a pull-request to cocoapods … I'll keep you informed.

**Comment by arytbk** [comment]
My podspec has been approved and merged, Sequencer is now a pod called (guess what!) "Sequencer".
You can see it here:
http://cocoapods.org/?q=sequencer

And it would be nice to add something like this in the README:

---

Installation
The recommended approach for installing Sequencer is via the CocoaPods package manager, as it provides flexible dependency management and dead simple installation.

Install CocoaPods if not already available:

$ [sudo] gem install cocoapods
$ pod setup

Edit your Podfile and add Sequencer:

$ edit Podfile
platform :ios, '5.0'
pod 'Sequencer'

Install into your Xcode project:

$ pod install

Add #include "Sequencer.h" to the top of classes that will use it.

---
