### ISSUE TITLE
Tag 1.0.1

### ISSUE THREAD

**Issue by arytbk** [berzniz/Sequencer#4]
Hi Tal,
You should now tag the current version (with updated README) as "1.0.1", and I'll then be able to update the pod spec file accordingly...

**Comment by berzniz** [comment]
Done. I'll created new tags as new features/bug-fixes come in (in the future).

**Comment by arytbk** [comment]
Great!
I submitted a request to Cocoapods too.

P.S: I live in Raanana, Israel…

**Comment by KanybekMomukeyev** [comment]
Thanks for the great work, simple class, but solves hard problems.

**Comment by berzniz** [comment]
Thanks! I'm glad you're finding it useful.
