### ISSUE TITLE
Swift 3 support!

### ISSUE THREAD

**Issue by anirudhamahale** [berzniz/Sequencer#7]
Thanks for a great library👍🏻
Is the support for swift3 is up?

**Comment by berzniz** [comment]
Unfortunately, I've not been working on iOS code lately and am not keeping up with the new versions of swift. The Sequencer is written in Obj-C and hopefully that doesn't break when Apple moves a long.

If you can verify it works that would be great. If it doesn't, I'm open for Pull Requests fixing what's wrong.

**Comment by anirudha-music** [comment]
Ya it works with swift 3.0
